flink:
  app:
    name: Sojourner Realtime Pipeline - RNO
    parallelism:
      default: 120
      source: 100
      event: 100
      session: 600
      pre-agent-ip: 120
      agent-ip: 120
      agent: 120
      ip: 120
      broadcast: 510
      metrics: 510
    slot-sharing-group:
      source-event-lvs: lvs
      source-event-slc: slc
      source-event-rno: rno
      session: session
      cross-session: cross-session
    operator-name:
      source:
        rno: Pathfinder RNO Source
        lvs: Pathfinder LVS Source
        slc: Pathfinder SLC Source
    uid:
      source:
        rno: pathfinder-rno-source
        lvs: pathfinder-lvs-source
        slc: pathfinder-slc-source
    data-skew:
      is-filter: true
      guid-set:
        - 17a61c8c16d0a9c509d4c64cffffff61
      pageid-set: []
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    hot-deploy: false
    source:
      from-timestamp: 0
      out-of-orderless-in-min: 3
      idle-source-timeout-in-min: 10
    sink:
      dc: rno
      kafka:
        topic:
          session:
            bot: behavior.totalv2.sojsession-bot-rno
            non-bot: behavior.totalv2.sojsession-nonbot-rno
          event:
            bot: behavior.totalv2.sojevent-bot-rno
            non-bot: behavior.totalv2.sojevent-nonbot-rno
            late: behavior.totalv2.sojevent-late-rno
          signature:
            agent-ip: behavior.totalv2.signature.agent-ip-rno
            agent: behavior.totalv2.signature.agent-rno
            ip: behavior.totalv2.signature.ip-rno
        subject:
          event: behavior.pulsarv2.sojevent.schema
          session: behavior.pulsarv2.sojsession.schema
        message-key:
          session: guid
          event: guid,pageId
          signature:
            ip: ip
            agent: userAgent
            agent-ip: userAgent

kafka:
  consumer:
    stream: behavior.pathfinder
    topic:
      - behavior.pathfinder.events.total
    group-id: sojourner-pathfinder-realtime
    bootstrap-servers:
      rno:
        - rhs-glrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      slc:
        - rhs-mwsvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
      lvs:
        - rhs-swsvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

    max-poll-records: 5000
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 8MB, default value is 64KB
    receive-buffer: 8388608
    fetch-max-wait-ms: 100
    # 10MB, default value is 1MB
    max-partitions-fetch-bytes: 10485760
    auto-offset-reset: latest

  producer:
    stream: behavior.totalv2
    producerId: sojourner
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

    batch-size: 524288
    acks: 1
    linger-ms: 50
    # 30s
    request-timeout-ms: 30000
    retries: 30
    buffer-memory: 268435456
    compression-type: lz4
    # 2min
    delivery-timeout-ms: 120000

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

zookeeper:
  enable: false
  sessionTimeoutMs: 15000
  connectionTimeoutMs: 5000
  maxRetries: 3
  baseSleepTimeMs: 1000
  namespace: sojourner

rest-client:
  base-url: https://sojubdportalservice.vip.ebay.com
  username: soj-flink-app

ua-parser-env: prod