kafka:
  consumer:
    topic:
      - behavior.totalv2.sojsession-nonbot-rno
    group-id: sojourner-total-dumper-rno

flink:
  app:
    name: Sojourner RNO Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    operator-name:
      source: Sojourner Total RNO Nonbot Session Source
      pass-through: RNO Byte To Nonbot Session
      assgin-watermark: RNO Nonbot Session Watermark Assign
      extract-watermark: RNO Nonbot Session Timestamp Extract
      session-split: RNO Nonbot Session Split
      sink:
        session:
          open: Sojourner Total RNO Nonbot Open Session Sink
          same-day: Sojourner Total RNO Nonbot Same Day Session Sink
          cross-day: Sojourner Total RNO Nonbot Cross Day Session Sink
        watermark: Sojourner Total RNO Nonbot Session Watermark Sink
    uid:
      source: sojourner-total-rno-nonbot-session-source
      pass-through: rno-byte-to-nonbot-session
      assgin-watermark: rno-nonbot-session-watermak-assign
      extract-watermark: rno-nonbot-session-timestamp-extract
      session-split: rno-nonbot-session-split
      sink:
        session:
          open: sojourner-total-rno-nonbot-open-session-sink
          same-day: sojourner-total-rno-nonbot-same-day-session-sink
          cross-day: sojourner-total-rno-nonbot-cross-day-session-sink
        watermark: sojourner-total-rno-nonbot-session-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-session-watermark-delay-time
    source:
      dc: rno
    sink:
      hdfs:
        path:
          open: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=nonbot
          same-day: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=nonbot
          cross-day: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=nonbot
        watermark-path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=nonbot
#      hdfs:
#        path:
#          open: hdfs://apollo-rno/sys/soj/ubd/sessions/category=open/type=nonbot
#          same-day: hdfs://apollo-rno/sys/soj/ubd/sessions/category=sameday/type=nonbot
#          cross-day: hdfs://apollo-rno/sys/soj/ubd/sessions/category=crossday/type=nonbot
#        watermark-path: hdfs://apollo-rno/sys/soj/ubd/watermark/sessions/type=nonbot


