kafka:
  consumer:
    topic:
      - behavior.totalv2.sojevent-nonbot-lvs
    group-id: sojourner-total-dumper-rno

flink:
  app:
    name: Sojourner RNO Non Bot Event HDFS Load Pipeline
    parallelism:
      source: 200
      sink:
        hdfs: 400
    operator-name:
      source: Sojourner Total RNO Nonbot Event Source
      pass-through: RNO Byte To Nonbot Event
      assgin-watermark: RNO Nonbot Event Watermark Assign
      extract-watermark: RNO Nonbot Event Timestamp Extract
      sink:
        event: Sojourner Total RNO Nonbot Event Sink
        watermark: Sojourner Total RNO Nonbot Event Watermark Sink
    uid:
      source: sojourner-total-rno-nonbot-event-source
      pass-through: rno-byte-to-nonbot-event
      assgin-watermark: rno-nonbot-event-watermak-assign
      extract-watermark: rno-nonbot-event-timestamp-extract
      sink:
        event: sojourner-total-rno-nonbot-event-sink
        watermark: sojourner-total-rno-nonbot-event-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-event-watermark-delay-time
    source:
      dc: lvs
    sink:
      hdfs:
        path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=nonbot
        watermark-path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=nonbot
#      hdfs:
#        path: hdfs://apollo-rno/sys/soj/ubd/events/type=nonbot
#        watermark-path: hdfs://apollo-rno/sys/soj/ubd/watermark/events/type=nonbot


