kafka:
  consumer:
    data-center: RNO
    stream: behavior.total.new
    topic:
      - behavior.total.new.sojevent.bot
    group-id:
      rno: sojourner-total-new-dumper
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092

flink:
  app:
    name: Sojourner RNO Bot Event HDFS Load Pipeline TEST
    parallelism:
      source: 150
      sink:
        hdfs: 300
    operator-name:
      source: Sojourner Total New RNO Bot Event Source
      pass-through: RNO Byte To Bot Event
      assgin-watermark: RNO Bot Event Watermark Assign
      extract-watermark: RNO Bot Event Timestamp Extract
      sink:
        event: Sojourner Total New RNO Bot Event Sink
        watermark: Sojourner Total New RNO Bot Event Watermark Sink
    uid:
      source: sojourner-total-new-rno-bot-event-source
      pass-through: rno-byte-to-bot-event
      assgin-watermark: rno-bot-event-watermak-assign
      extract-watermark: rno-bot-event-timestamp-extract
      sink:
        event: sojourner-total-new-rno-bot-event-sink
        watermark: sojourner-total-new-rno-bot-event-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/test/events/type=bot
    watermark-path: hdfs://apollo-rno/sys/soj/ubd/test/watermark/events/type=bot