kafka:
  consumer:
    topic:
      - behavior.totalv2.sojsession-bot-rno
    group-id: sojourner-total-dumper-rno

flink:
  app:
    name: Sojourner Bot Event HDFS Load Pipeline - LVS
    parallelism:
      source: 150
      sink:
        hdfs: 300
    operator-name:
      source: Sojourner Total LVS Bot Event Source
      pass-through: LVS Byte To Bot Event
      assgin-watermark: LVS Bot Event Watermark Assign
      extract-watermark: LVS Bot Event Timestamp Extract
      sink:
        event: Sojourner Total LVS Bot Event Sink
        watermark: Sojourner Total LVS Bot Event Watermark Sink
    uid:
      source: sojourner-total-lvs-bot-event-source
      pass-through: lvs-byte-to-bot-event
      assgin-watermark: lvs-bot-event-watermak-assign
      extract-watermark: lvs-bot-event-timestamp-extract
      sink:
        event: sojourner-total-lvs-bot-event-sink
        watermark: sojourner-total-lvs-bot-event-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time
    source:
      dc: lvs
    sink:
      hdfs:
        path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=bot
        watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=bot
#      hdfs:
#        path: hdfs://hercules/sys/soj/ubd/events/type=bot
#        watermark-path: hdfs://hercules/sys/soj/ubd/watermark/events/type=bot