kafka:
  consumer:
    topic:
      - behavior.totalv2.sojevent-bot-lvs
    group-id:  sojourner-total-dumper-rno

flink:
  app:
    name: Sojourner RNO Bot Event HDFS Load Pipeline
    parallelism:
      source: 150
      sink:
        hdfs: 300
    operator-name:
      source: Sojourner Total RNO Bot Event Source
      pass-through: RNO Byte To Bot Event
      assgin-watermark: RNO Bot Event Watermark Assign
      extract-watermark: RNO Bot Event Timestamp Extract
      sink:
        event: Sojourner Total RNO Bot Event Sink
        watermark: Sojourner Total RNO Bot Event Watermark Sink
    uid:
      source: sojourner-total-rno-bot-event-source
      pass-through: rno-byte-to-bot-event
      assgin-watermark: rno-bot-event-watermak-assign
      extract-watermark: rno-bot-event-timestamp-extract
      sink:
        event: sojourner-total-rno-bot-event-sink
        watermark: sojourner-total-rno-bot-event-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time
    source:
      dc: lvs
    sink:
      hdfs:
        path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=bot
        watermark-path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=bot
#      hdfs:
#        path: hdfs://apollo-rno/sys/soj/ubd/events/type=bot
#        watermark-path: hdfs://apollo-rno/sys/soj/ubd/watermark/events/type=bot


