flink:
  app:
    name: Sojourner Distributor - RNO
    parallelism:
      source: 200
      sink-kafka: 200
    checkpoint:
      data-dir: /opt/flink/sojourner/distributor/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    source:
      dc: rno
      operator-name: Non-bot SojEvent Source
      from-timestamp: 0
      out-of-orderless-in-min: 0
    sink:
      dc: rno
      operator-name: Non-bot SojEvent Sink
      kafka:
        topic: behavior.pulsar.sojevent.deadletter

kafka:
  consumer:
    stream: behavior.totalv2
    group-id: sojourner-distributor-rno
    topic:
      - behavior.totalv2.sojevent-nonbot-rno
      - behavior.totalv2.sojevent-nonbot-lvs
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest

  producer:
    stream: behavior.pulsar
    bootstrap-servers:
      rno:
        - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      slc:
        - rhs-qisvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
    batch-size: 524288
    acks: 1
    linger-ms: 50
    # 30s
    request-timeout-ms: 30000
    retries: 30
    buffer-memory: 268435456
    compression-type: lz4
    # 2min
    delivery-timeout-ms: 120000

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

rest-client:
  base-url: https://sojsvc.vip.ebay.com
  username: soj-flink-app
  config:
    pull-interval: 30000
    profile: prod
